name: KillTracker
version: 1.3.2
author: bittiez
main: US.bittiez.KillTracker.main
api-version: 1.15
commands:
  killtracker:
    description: This will display your KillTracker stats
    usage: /killtracker stats